### ISSUE TITLE
Ubuntu password

### ISSUE THREAD

**Issue by danielespitiacol** [MoebiusTech/ROS_STM32#1]
Hello, I have downloaded the raspberry pi image from google drive but the operating system is in chinese.
To change the language I need the root password for the user: mbsrobot

**Comment by MoebiusTech** [comment]
password: 123456


moebius@mbeus.com
 
From: Daniel Espita
Date: 2020-12-30 21:29
To: MoebiusTech/ROS_STM32
CC: Subscribed
Subject: [MoebiusTech/ROS_STM32] Ubuntu password (#1)
Hello, I have downloaded the raspberry pi image from google drive but the operating system is in chinese.
To change the language I need the root password for the user: mbsrobot
